Initial go sovler

diff --git a/.gitHooks/pre-push b/.gitHooks/pre-push
--- a/.gitHooks/pre-push
+++ b/.gitHooks/pre-push
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Run the test script
+# Run the python test script
 make -C python_poc
 EXIT=$?
 
@@ -8,7 +8,17 @@ EXIT=$?
 if [ $EXIT -ne 0 ]; then
     echo "ERROR: Pre-push checks failed. Push aborted."
     exit 1
-else
-    echo "All checks passed. Proceeding with push."
-    exit 0
 fi
+
+# Run the go test script
+make -C .
+EXIT=$?
+
+# Check if the script succeeded
+if [ $EXIT -ne 0 ]; then
+    echo "ERROR: Pre-push checks failed. Push aborted."
+    exit 1
+fi
+
+echo "All checks passed. Proceeding with push."
+exit 0
